---
- hosts: cisco
  gather_facts: no
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: ansible.netcommon.ios
    ansible_user: "{{ lookup('env','DEVICE_USERNAME') }}"
    ansible_password: "{{ lookup('env','DEVICE_PASSWORD') }}"
    ansible_ssh_pass: "{{ lookup('env','DEVICE_SECRET') }}"
    correct_values:
      '1': {'role': 'active', 'priority': '1'}
      '2': {'role': 'member', 'priority': '1'}
      '3': {'role': 'standby', 'priority': '1'}
  tasks:
    - name: run show switch command
      ansible.netcommon.cli_command:
        command: show switch
      register: result

    - name: Parse command output and write results to file
      block:
        - name: Extract switch details
          set_fact:
            switch_info: "{{ item.split() }}"
          loop: "{{ result.stdout_lines[0] }}"
          when: item | regex_search('^\*?\d')
          register: switch_details

        - name: Check each switch
          block:
            - name: Set facts
              set_fact:
                role: "{{ item['ansible_facts']['switch_info'][1]|lower }}"
                priority: "{{ item['ansible_facts']['switch_info'][3]|lower }}"
                switch: "{{ item['ansible_facts']['switch_info'][0]|replace('*','') }}"
              
            - name: Check if role and priority match expected values
              set_fact:
                result: "PASS - Switch {{ switch }}: Role {{ role }}, Priority {{ priority }}"
              when: role == correct_values[switch]['role'] and priority == correct_values[switch]['priority']
            
            - name: Write pass result to file
              copy:
                content: "{{ result }}"
                dest: "/path/to/output.txt"
              when: role == correct_values[switch]['role'] and priority == correct_values[switch]['priority']
            
            - name: Check if role and priority do not match expected values
              set_fact:
                result: "FAIL - Switch {{ switch }}: Expected Role {{ correct_values[switch]['role'] }}, Priority {{ correct_values[switch]['priority'] }}. Got Role {{ role }}, Priority {{ priority }}"
              when: role != correct_values[switch]['role'] or priority != correct_values[switch]['priority']
            
            - name: Write fail result to file
              copy:
                content: "{{ result }}"
                dest: "/path/to/output.txt"
              when: role != correct_values[switch]['role'] or priority != correct_values[switch]['priority']
          loop: "{{ switch_details.results }}"
      when: result.stdout[0] is search('----')
